/* Generated By:JavaCC: Do not edit this line. HtmlTokenParserConstants.java */
/*
 * Priki - Prevalent Wiki
 * Copyright (c) 2005 Priki 
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 * http://www.gnu.org/copyleft/gpl.html
 *
 * @author Vitor Fernando Pamplona - vitor@babaxp.org
 *
 */

package org.priki.format.compiler;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HtmlTokenParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int A_TAG = 5;
  /** RegularExpression Id. */
  int CODE_TAG = 6;
  /** RegularExpression Id. */
  int PRE_TAG = 7;
  /** RegularExpression Id. */
  int OPEN_A_TAG = 8;
  /** RegularExpression Id. */
  int OPEN_PRE_TAG = 9;
  /** RegularExpression Id. */
  int OPEN_CODE_TAG = 10;
  /** RegularExpression Id. */
  int HTMLTAG = 11;
  /** RegularExpression Id. */
  int SYMBOL = 12;
  /** RegularExpression Id. */
  int EMAIL = 13;
  /** RegularExpression Id. */
  int LINK = 14;
  /** RegularExpression Id. */
  int WIKIWORD = 15;
  /** RegularExpression Id. */
  int NUMBER = 16;
  /** RegularExpression Id. */
  int TIME = 17;
  /** RegularExpression Id. */
  int DATE = 18;
  /** RegularExpression Id. */
  int CODE = 19;
  /** RegularExpression Id. */
  int PROPERTIES = 20;
  /** RegularExpression Id. */
  int PROPERTY = 21;
  /** RegularExpression Id. */
  int NAMES = 22;
  /** RegularExpression Id. */
  int SPACE = 23;
  /** RegularExpression Id. */
  int SPACES = 24;
  /** RegularExpression Id. */
  int LETTER = 25;
  /** RegularExpression Id. */
  int NOTLETTERORDIGIT = 26;
  /** RegularExpression Id. */
  int DIGIT = 27;
  /** RegularExpression Id. */
  int SOMECHAR = 28;
  /** RegularExpression Id. */
  int STRING = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "<A_TAG>",
    "<CODE_TAG>",
    "<PRE_TAG>",
    "<OPEN_A_TAG>",
    "<OPEN_PRE_TAG>",
    "<OPEN_CODE_TAG>",
    "<HTMLTAG>",
    "<SYMBOL>",
    "<EMAIL>",
    "<LINK>",
    "<WIKIWORD>",
    "<NUMBER>",
    "<TIME>",
    "<DATE>",
    "<CODE>",
    "<PROPERTIES>",
    "<PROPERTY>",
    "<NAMES>",
    "<SPACE>",
    "<SPACES>",
    "<LETTER>",
    "<NOTLETTERORDIGIT>",
    "<DIGIT>",
    "<SOMECHAR>",
    "<STRING>",
  };

}
